---
-   hosts: aws
    tasks:
#        -   name: Copy repo file
#            copy: src=/etc/yum/repos.d/rhel.repo dest=/etc/yum.repos.d/rhel.repo
        -   name: Install httpd
            action: yum name=httpd state=installed
        -   name: get php/html from git
            action: src=/root/files/files/index.php desc=/var/www/html/index.php
        -   name: start apache
            service:
                name: httpd
                state: started
        -   name: Install php
            action: yum name=php state=installed
#        -   name: Install php-mysql
#            action: yum name=php-mysql state=installed
#        -   name: Install php-fpm
#            action: yum name=php-fpm state=installed

